apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-service-stack

resources:
  - ../../../base/ui

images:
  - name: bridge-gateway-ui
    newName: harbor.binari.digital/bridge-gateway/bridge-gateway-ui
    newTag: dev-latest
