apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-service-stack

commonLabels:
  app.kubernetes.io/name: bridge-gateway-ui
  app.kubernetes.io/part-of: bridge-ecosystem

resources:
  - deployment.yaml
  - configmap.yaml
