apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-gateway-config
  labels:
    app: bridge-gateway
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "4000"
  ORCHESTRA_BASE_URL: "http://bridge-orchestra-api.bridge-service-stack.svc.cluster.local:8080"
  CUSTODY_BASE_URL: "http://bridge-custody-api.bridge-service-stack.svc.cluster.local:8081"
  WALLET_BASE_URL: "http://bridge-wallet.bridge-service-stack.svc.cluster.local:8080"
  REDIS_HOST: "bridge-redis-master.bridge-service-stack.svc.cluster.local"
  REDIS_PORT: "6379"
  VAULT_ADDR: "https://vault.binari.digital"
  VAULT_ENABLED: "false"
